[features]
seeds = false
skip-lint = false

[programs.localnet]
constant = "CRB7SpuUc8VVC2uwmVHVBq7c7HcNZ926kfy5bs4hapua"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
client = "yarn run ts-node client/*.ts"
